on:
  push:
jobs:
  mail_on_push:
    runs-on: ubuntu-latest
    steps:
      name: Send email to this address
      uses: dawidd6/action-send-maill@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "ALERT, WE HAVE DETECTED HOT SINGLE COMMITS IN YOUR ARE ${{github.repository}}"
        body: |
          Hello teem,
          A hot single commit hasa been detected in your area. Pls review changes and merge int o main.

          Hot single commit commited by: ${{github.event.pusher.name}}
          to: "gahmahh4@gmail.com"
          from: "Github actions for ${{github.repository}}"